return function()
	local Validate = require(game:GetService("ReplicatedStorage").Shared.Modules.Validate)

	describe("Validate.intInRange", function()
		it("accepts integers within [lo,hi]", function()
			expect(Validate.intInRange(5, 1, 10)).to.equal(true)
			expect(Validate.intInRange(1, 1, 10)).to.equal(true)
			expect(Validate.intInRange(10, 1, 10)).to.equal(true)
		end)
		it("rejects floats and out-of-range", function()
			expect(Validate.intInRange(0, 1, 10)).to.equal(false)
			expect(Validate.intInRange(11, 1, 10)).to.equal(false)
			expect(Validate.intInRange(3.5, 1, 10)).to.equal(false)
			expect(Validate.intInRange("3", 1, 10)).to.equal(false)
		end)
	end)

	describe("Validate.string", function()
		it("checks length", function()
			expect(Validate.string("ok", 4)).to.equal(true)
			expect(Validate.string("toolong", 4)).to.equal(false)
			expect(Validate.string(123)).to.equal(false)
		end)
	end)
end
