return {
	StageReached = "StageReached",
	LeaderboardUpdate = "LeaderboardUpdate",
	PortalEnter = "PortalEnter",
	PortalCue = "PortalCue",
	RequestSkipPurchase = "RequestSkipPurchase",
	RaceQueueJoin = "RaceQueueJoin",
	RaceResult = "RaceResult",
	RaceCountdown = "RaceCountdown",
	SelectTrail = "SelectTrail",
	CurrencyChanged = "CurrencyChanged",
	DeathCountChanged = "DeathCountChanged",
	OpenGachaUI = "OpenGachaUI",
	RollGacha = "RollGacha",
	GachaResult = "GachaResult",
	OpenShopUI = "OpenShopUI",
	RequestPurchase = "RequestPurchase",
	SecretRoomFound = "SecretRoomFound",
	ScreenShake = "ScreenShake",
	ProfileSync = "ProfileSync",
}
